#!/usr/bin/env python3
"""
K8s Function Generator - Step 2: Review & Validate
Second AI reviews K8s functions generated in Step 1 for accuracy and consistency.
"""

import argparse
import json
import logging
import os
import time
from pathlib import Path
from typing import Dict

import openai
from openai import OpenAI
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

K8S_NAMING_STANDARDS = """
KUBERNETES FUNCTION NAMING STANDARDS & BEST PRACTICES:

PATTERN: k8s_<resource>_<check_description>

VALID RESOURCES:
- rbac: RBAC roles, bindings, service accounts
- networkpolicy: Network policies, ingress/egress rules
- pod: Pod security, SecurityContext
- secret: Secrets management
- etcd: etcd security and encryption
- apiserver: API server configuration
- admission: Admission controllers, webhooks
- image: Container image security
- service: Service configurations
- ingress: Ingress controller security
- config: ConfigMaps, configuration management
- audit: Audit logging and policies
- namespace: Namespace isolation and security

NAMING BEST PRACTICES:
✓ Descriptive: k8s_rbac_cluster_admin_role_not_used (GOOD)
✗ Vague: k8s_rbac_check (BAD)

✓ Specific action: k8s_pod_security_context_non_root (GOOD)
✗ Generic: k8s_pod_secure (BAD)

✓ Clear pass/fail: k8s_networkpolicy_default_deny_ingress (GOOD)
✗ Ambiguous: k8s_networkpolicy_configured (BAD)

✓ Consistent pattern: k8s_admission_controller_pod_security_enabled (GOOD)
✗ Inconsistent: k8s_pod_sec_admission_ctrl_on (BAD)

COMMON CHECKS BY DOMAIN:

RBAC:
- k8s_rbac_no_cluster_admin_binding
- k8s_rbac_least_privilege_enforcement
- k8s_rbac_service_account_token_automount_disabled
- k8s_rbac_wildcard_permissions_restricted

NetworkPolicy:
- k8s_networkpolicy_default_deny_ingress
- k8s_networkpolicy_default_deny_egress
- k8s_networkpolicy_pod_selector_defined

Pod Security:
- k8s_pod_security_context_non_root
- k8s_pod_host_network_disabled
- k8s_pod_privileged_container_disabled
- k8s_pod_security_standard_restricted

Secrets:
- k8s_secret_encryption_at_rest_enabled
- k8s_secret_not_in_env_variables
- k8s_secret_external_manager_configured

etcd:
- k8s_etcd_encryption_enabled
- k8s_etcd_tls_enabled
- k8s_etcd_backup_configured

API Server:
- k8s_apiserver_authentication_enabled
- k8s_apiserver_authorization_mode_rbac
- k8s_apiserver_anonymous_auth_disabled
- k8s_apiserver_audit_logging_enabled

Images:
- k8s_image_scan_on_admission
- k8s_image_pull_policy_always
- k8s_image_latest_tag_prohibited
- k8s_image_vulnerability_scanning_enabled
"""

@retry(
    wait=wait_exponential(multiplier=1, min=2, max=30),
    stop=stop_after_attempt(4),
    retry=retry_if_exception_type((openai.APIError, openai.APIConnectionError, openai.RateLimitError))
)
def review_k8s_functions(step1_result: Dict, framework_name: str) -> Dict:
    """Review K8s functions generated in Step 1."""
    api_key = os.environ["OPENAI_API_KEY"].strip()
    client = OpenAI(api_key=api_key, timeout=90.0)
    
    control_id = step1_result.get('control_id', 'Unknown')
    title = step1_result.get('title', '')
    k8s_applicable = step1_result.get('k8s_applicable', False)
    k8s_functions = step1_result.get('k8s_functions', [])
    step1_reasoning = step1_result.get('reasoning', '')
    step1_confidence = step1_result.get('confidence', '')
    
    if not k8s_applicable:
        return {
            "control_id": control_id,
            "review_status": "NOT_APPLICABLE",
            "k8s_applicable": False,
            "validated_functions": [],
            "review_notes": "Step 1 determined not applicable to K8s",
            "agreement_with_step1": True
        }
    
    step1_json = json.dumps(step1_result, indent=2)
    
    system_message = (
        "You are a senior Kubernetes security reviewer and compliance expert. "
        "Your role is to critically review K8s security function names generated by another AI, "
        "ensuring they are accurate, follow naming conventions, and properly map to K8s security controls. "
        "You should validate technical accuracy, naming consistency, and practical implementability."
    )
    
    user_message = f"""FRAMEWORK: {framework_name}
CONTROL: {control_id} - {title}

{K8S_NAMING_STANDARDS}

STEP 1 RESULTS (TO REVIEW):
{step1_json}

YOUR TASK:
Critically review the K8s functions generated in Step 1. Verify:

1. **K8s Applicability**: Is this control truly applicable to Kubernetes?
   - Does it map to actual K8s security features?
   - Or is it cloud-specific with no K8s equivalent?

2. **Function Naming**: Do function names follow conventions?
   - Pattern: k8s_<resource>_<check_description>
   - Are they descriptive and specific?
   - Do they clearly indicate what passes/fails?

3. **Technical Accuracy**: Are the functions technically correct?
   - Do they map to real K8s security controls?
   - Are there better alternatives?
   - Are any functions missing?

4. **Consistency**: Are names consistent with similar checks?
   - Check against the common patterns listed above

REVIEW DECISION:
- **APPROVE**: Functions are accurate and well-named
- **APPROVE_WITH_CHANGES**: Mostly good but needs refinements
- **REJECT**: Significant issues, needs major revision
- **NOT_APPLICABLE**: Disagree with Step 1, not applicable to K8s

OUTPUT REQUIREMENTS:
Return JSON with:
{{
  "review_status": "APPROVE|APPROVE_WITH_CHANGES|REJECT|NOT_APPLICABLE",
  "k8s_applicable": true/false,
  "validated_functions": ["corrected or approved function list"],
  "changes_made": ["list of changes if any"],
  "review_notes": "Detailed explanation of review decision",
  "agreement_with_step1": true/false,
  "technical_concerns": ["list any technical issues"],
  "naming_improvements": ["suggestions for better names if any"]
}}

EXAMPLES OF GOOD REVIEWS:

Example 1 - Approve:
{{
  "review_status": "APPROVE",
  "k8s_applicable": true,
  "validated_functions": ["k8s_rbac_no_cluster_admin_binding", "k8s_rbac_least_privilege_enforcement"],
  "changes_made": [],
  "review_notes": "Functions accurately map IAM privilege controls to K8s RBAC. Naming is clear and follows conventions.",
  "agreement_with_step1": true
}}

Example 2 - Approve with Changes:
{{
  "review_status": "APPROVE_WITH_CHANGES",
  "k8s_applicable": true,
  "validated_functions": ["k8s_networkpolicy_default_deny_ingress", "k8s_networkpolicy_default_deny_egress"],
  "changes_made": ["Changed k8s_network_ingress_denied to k8s_networkpolicy_default_deny_ingress for consistency"],
  "review_notes": "Good mapping but improved naming for clarity and consistency with K8s terminology",
  "agreement_with_step1": true,
  "naming_improvements": ["Use 'networkpolicy' instead of 'network' for resource name"]
}}

Example 3 - Not Applicable:
{{
  "review_status": "NOT_APPLICABLE",
  "k8s_applicable": false,
  "validated_functions": [],
  "changes_made": [],
  "review_notes": "This control is specific to cloud billing/cost management which has no K8s equivalent",
  "agreement_with_step1": false
}}

Perform your review now:"""

    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": system_message},
                {"role": "user", "content": user_message}
            ],
            response_format={"type": "json_object"},
            temperature=0.2,  # Lower temperature for more consistent review
            max_tokens=1200
        )
        
        result = json.loads(response.choices[0].message.content)
        result["control_id"] = control_id
        result["title"] = title
        result["step1_functions"] = k8s_functions
        result["step1_reasoning"] = step1_reasoning
        
        return result
        
    except Exception as e:
        logging.error(f"Error reviewing K8s functions for {control_id}: {str(e)}")
        return {
            "control_id": control_id,
            "review_status": "ERROR",
            "k8s_applicable": k8s_applicable,
            "validated_functions": k8s_functions,  # Keep original on error
            "review_notes": f"Error during review: {str(e)}",
            "agreement_with_step1": True  # Default to agreement on error
        }


def process_step1_results(step1_dir: str, output_dir: str, framework_name: str):
    """Process Step 1 JSON files and generate Step 2 reviews."""
    
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    step1_path = Path(step1_dir)
    json_files = list(step1_path.glob("*.json"))
    
    logging.info(f"Reviewing {len(json_files)} Step 1 results for {framework_name}")
    
    results = []
    approved_count = 0
    changed_count = 0
    rejected_count = 0
    na_count = 0
    
    for idx, json_file in enumerate(json_files, 1):
        logging.info(f"[{idx}/{len(json_files)}] Reviewing: {json_file.name}")
        
        # Load Step 1 result
        with open(json_file, 'r', encoding='utf-8') as f:
            step1_result = json.load(f)
        
        # Review
        review_result = review_k8s_functions(step1_result, framework_name)
        results.append(review_result)
        
        # Count by status
        status = review_result.get('review_status', '')
        if status == 'APPROVE':
            approved_count += 1
        elif status == 'APPROVE_WITH_CHANGES':
            changed_count += 1
        elif status == 'REJECT':
            rejected_count += 1
        elif status == 'NOT_APPLICABLE':
            na_count += 1
        
        # Save review result
        output_file = Path(output_dir) / json_file.name
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(review_result, f, indent=2, ensure_ascii=False)
        
        # Rate limiting
        time.sleep(0.5)
    
    # Summary
    logging.info(f"\n{'='*80}")
    logging.info(f"STEP 2 COMPLETE - {framework_name}")
    logging.info(f"  Total reviewed: {len(json_files)}")
    logging.info(f"  Approved: {approved_count}")
    logging.info(f"  Approved with changes: {changed_count}")
    logging.info(f"  Rejected: {rejected_count}")
    logging.info(f"  Not applicable: {na_count}")
    logging.info(f"  Results saved to: {output_dir}")
    logging.info(f"{'='*80}\n")


def main():
    parser = argparse.ArgumentParser(description='Review K8s functions - Step 2')
    parser.add_argument('--step1-dir', required=True, help='Directory with Step 1 JSON results')
    parser.add_argument('--output-dir', required=True, help='Output directory for Step 2 reviews')
    parser.add_argument('--framework', required=True, help='Framework name')
    
    args = parser.parse_args()
    
    if not os.getenv('OPENAI_API_KEY'):
        logging.error("OPENAI_API_KEY environment variable not set")
        return 1
    
    process_step1_results(args.step1_dir, args.output_dir, args.framework)
    return 0


if __name__ == "__main__":
    exit(main())

